---
root: true
env:
  browser: true
extends:
  - airbnb-base
  - prettier
rules:
  valid-jsdoc: error
  import/no-extraneous-dependencies:
    - error
    - peerDependencies: true
overrides:
  - files:
      - build-config/**
      - src/**/*.test.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
          peerDependencies: true
  - files:
      - src/**/*.test.js
    env:
      jest: true
