import { defineConfig } from 'eslint/config';
import eslintConfigXo from 'eslint-config-xo';
import vitest from '@vitest/eslint-plugin';

export default defineConfig([
  {
    ignores: [
      // Auto-generated by standard-version; not covered by .gitignore.
      'CHANGELOG.md',
      // Git worktrees excluded via .git/info/exclude, not .gitignore.
      '.claude/worktrees/**',
    ],
  },
  ...eslintConfigXo({
    browser: true,
    prettier: 'compat',
    gitignore: import.meta.url,
  }),
  {
    rules: {
      // But in eslintConfigXo, the rule should be disabled because
      // it's incompatible with prettier.
      // C.f. https://github.com/xojs/xo/issues/889.
      '@stylistic/no-mixed-operators': 'off',
    },
  },
  {
    files: ['demo/**'],
    rules: {
      // MarkingMenu is a factory function (an arrow function under the hood),
      // not a constructor -- `new MarkingMenu(...)` would throw.
      'new-cap': ['error', { capIsNewExceptions: ['MarkingMenu'] }],
      // No project preview image exists yet to use as og:image; og:title,
      // og:type, and og:url are already set above.
      '@html-eslint/require-open-graph-protocol': 'off',
    },
  },
  {
    files: ['src/**/*.test.js'],
    plugins: { vitest },
    languageOptions: {
      globals: vitest.environments.env.globals,
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // Rxjs-marbles' `m.expect(...)` is this suite's second assertion entry
      // point alongside the ambient `expect`; the rule can't infer that statically.
      'vitest/expect-expect': [
        'error',
        { assertFunctionNames: ['expect', 'm.expect'] },
      ],
      // Describe() is called with an imported function reference in some
      // files; the rule can't resolve the import to confirm it's a function.
      'vitest/valid-title': ['error', { allowArguments: true }],
      // These test suites use a `*Notif` naming convention for local
      // notification-object factory helpers; none of them are constructors.
      'new-cap': [
        'error',
        {
          capIsNewExceptions: ['Notif', 'OpenNotif', 'MNotif', 'EndNotif'],
        },
      ],
    },
  },
]);
