import vitest from '@vitest/eslint-plugin';
import eslintConfigXo from 'eslint-config-xo';
import importX from 'eslint-plugin-import-x';
import playwright from 'eslint-plugin-playwright';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  {
    ignores: [
      // Auto-generated by standard-version; not covered by .gitignore.
      'CHANGELOG.md',
      // Git worktrees excluded via .git/info/exclude, not .gitignore.
      '.claude/worktrees/**',
      // Deliberately outside any tsconfig project: it's a consumer fixture
      // typechecked by scripts/smoke-test.ts against the published package,
      // not against source, so type-aware linting doesn't apply to it.
      'smoke-test/**',
    ],
  },
  ...eslintConfigXo({
    browser: true,
    prettier: 'compat',
    gitignore: import.meta.url,
  }),
  {
    plugins: { 'import-x': importX },
    rules: {
      // Disabled because it conflicts with prettier.
      // C.f. https://github.com/xojs/xo/issues/889.
      '@stylistic/no-mixed-operators': 'off',

      // Import order is owned by @ianvs/prettier-plugin-sort-imports (c.f.
      // prettier.config.ts) and enforced by `yarn format:check`. This rule
      // disagrees with it: `marking-menu` is this package's own name, so once
      // dist/ is built, Node self-reference resolution makes import-x classify
      // it as an `internal` import and sort it last (behind third-party and
      // even relative imports), while prettier sorts it with third-party
      // modules. Keeping both means `eslint --fix` and `prettier --write` undo
      // each other, and that lint results depend on whether dist/ exists —
      // which is why this only ever failed locally, never on CI.
      'import-x/order': 'off',

      // This repo uses many factory functions, that starts with a capital letter, but are not classes.
      'new-cap': 'off',

      // This repo uses named exports only (c.f. bcb1332).
      'import-x/no-default-export': 'error',

      // This is a browser library. Node is a development tool pinned in
      // .tool-versions, not a supported runtime of the published package.
      'package-json/require-engines': 'off',
    },
  },
  {
    // The @typescript-eslint plugin is only registered for TypeScript files.
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      '@typescript-eslint/non-nullable-type-assertion-style': 'off',
      // The codebase models "no item" with `null` (recognizer results, root
      // MMItem fields, ...) and tests assert on it. Banning `null` types
      // would force inaccurate `undefined` annotations. Keep the rest of
      // XO's restricted types.
      '@typescript-eslint/no-restricted-types': [
        'error',
        {
          types: {
            object: {
              message:
                'The `object` type is hard to use. Use `Record<string, unknown>` instead. See: https://github.com/typescript-eslint/typescript-eslint/pull/848',
              fixWith: 'Record<string, unknown>',
            },
            Buffer: {
              message:
                'Use Uint8Array instead. See: https://sindresorhus.com/blog/goodbye-nodejs-buffer',
              suggest: ['Uint8Array'],
            },
            '[]': "Don't use the empty array type `[]`. It only allows empty arrays. Use `SomeType[]` instead.",
            '[[]]':
              "Don't use `[[]]`. It only allows an array with a single element which is an empty array. Use `SomeType[][]` instead.",
            '[[[]]]': "Don't use `[[[]]]`. Use `SomeType[][][]` instead.",
          },
        },
      ],
    },
  },
  {
    // Only test code may reach for `Symbol.dispose`/`Symbol.asyncDispose`:
    // shipped code must not require `using` of consumers, so the rule stays on
    // everywhere else and is the thing that catches a lapse. It flags both,
    // its `Symbol` list predating Explicit Resource Management, and it takes
    // no allowlist option, hence disabling it wholesale for these files.
    files: [
      'src/**/*.test.ts',
      'src/**/*.test-d.ts',
      'src/**/__fixtures__/**',
      'e2e/**',
    ],
    rules: {
      'unicorn/no-nonstandard-builtin-properties': 'off',
    },
  },
  {
    // Vite/Vitest/Prettier/Playwright config files must use a default
    // export; that's the contract those tools require.
    files: ['*.config.{js,ts}', 'e2e/*.config.{js,ts}'],
    rules: {
      'import-x/no-default-export': 'off',
    },
  },
  {
    // `baseURL` is Playwright's own option name, not ours to rename.
    files: ['e2e/playwright.config.ts'],
    rules: {
      '@typescript-eslint/naming-convention': 'off',
    },
  },
  {
    files: ['demo/**'],
    rules: {
      // No project preview image exists yet to use as og:image; og:title,
      // og:type, and og:url are already set above.
      '@html-eslint/require-open-graph-protocol': 'off',
    },
  },
  {
    files: ['e2e/fixture/**'],
    rules: {
      // The fixture is a test harness, not a public page: it has no
      // SEO/social surface to describe.
      '@html-eslint/require-meta-description': 'off',
      '@html-eslint/require-open-graph-protocol': 'off',
    },
  },
  {
    files: ['src/**/__fixtures__/**'],
    rules: {
      // `__fixtures__` (double underscore, both sides) is this repo's
      // established name for a directory of test-only helpers/data (see
      // `src/recognizer/__fixtures__`), predating this rule ever seeing a
      // `.ts` file directly inside one. Kebab-case doesn't allow it.
      'unicorn/filename-case': 'off',
    },
  },
  {
    files: ['src/**/*.test.{js,ts}'],
    plugins: { vitest },
    languageOptions: {
      globals: vitest.environments.env.globals,
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // Rxjs-marbles' `m.expect(...)` is this suite's second assertion entry
      // point alongside the ambient `expect`; the rule can't infer that statically.
      'vitest/expect-expect': [
        'error',
        { assertFunctionNames: ['expect', 'm.expect'] },
      ],
      // Describe() is called with an imported function reference in some
      // files; the rule can't resolve the import to confirm it's a function.
      'vitest/valid-title': ['error', { allowArguments: true }],
    },
  },
  {
    files: ['e2e/**/*.ts'],
    plugins: { playwright },
    rules: {
      ...playwright.configs['flat/recommended'].rules,
    },
  },
]);
