import vitest from '@vitest/eslint-plugin';
import eslintConfigXo from 'eslint-config-xo';
import importX from 'eslint-plugin-import-x';
import reactHooks from 'eslint-plugin-react-hooks';
import { defineConfig, globalIgnores } from 'eslint/config';
import skillsLock from './skills-lock.json' with { type: 'json' };

export default defineConfig([
  ...eslintConfigXo({
    browser: true,
    prettier: 'compat',
    gitignore: import.meta.url,
  }),
  globalIgnores([
    // Auto-generated by standard-version; not covered by .gitignore.
    'CHANGELOG.md',
    // Installed skills, kept byte for byte as their sources provide them.
    ...Object.keys(skillsLock.skills).map(
      (name) => `.agents/skills/${name}/**`,
    ),
    // Git worktrees excluded via .git/info/exclude, not .gitignore.
    '.claude/worktrees/**',
    // Deliberately outside any tsconfig project: it's a consumer fixture
    // typechecked by scripts/smoke-test.ts against the published package,
    // not against source, so type-aware linting doesn't apply to it.
    'smoke-test/**',
    // Vendored shadcn/ui components, kept byte for byte as the registry
    // serves them so the next copy is a plain overwrite. `.prettierignore`
    // leaves them alone for the same reason.
    'demo/playground/components/ui/**',
    // The built library itself, symlinked in for the browser (see
    // `demo/tsconfig.json`); already linted as its own source.
    'demo/lib/**',
  ]),
  {
    plugins: { 'import-x': importX },
    rules: {
      // Disabled because it conflicts with prettier.
      // C.f. https://github.com/xojs/xo/issues/889.
      '@stylistic/no-mixed-operators': 'off',

      // Import order is owned by @ianvs/prettier-plugin-sort-imports (c.f.
      // prettier.config.ts) and enforced by `yarn format:check`. This rule
      // disagrees with it: `marking-menu` is this package's own name, so once
      // dist/ is built, Node self-reference resolution makes import-x classify
      // it as an `internal` import and sort it last (behind third-party and
      // even relative imports), while prettier sorts it with third-party
      // modules. Keeping both means `eslint --fix` and `prettier --write` undo
      // each other, and that lint results depend on whether dist/ exists —
      // which is why this only ever failed locally, never on CI.
      'import-x/order': 'off',

      // This repo uses many factory functions, that starts with a capital letter, but are not classes.
      'new-cap': 'off',

      // This repo uses named exports only (c.f. bcb1332).
      'import-x/no-default-export': 'error',

      // This is a browser library. Node is a development tool pinned in
      // .tool-versions, not a supported runtime of the published package.
      'package-json/require-engines': 'off',
    },
  },
  {
    // The @typescript-eslint plugin is only registered for TypeScript files.
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      '@typescript-eslint/non-nullable-type-assertion-style': 'off',
      // No override needed: eslint-config-xo already restricts `null` (among
      // other types) here by default.
    },
  },
  {
    // Off by default in eslint-config-xo (c.f. its plugins-rules.js); this
    // codebase bans `null` in favor of `undefined`.
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}'],
    rules: {
      'unicorn/no-null': ['error', { checkStrictEquality: true }],
    },
  },
  {
    // Only test code may reach for `Symbol.dispose`/`Symbol.asyncDispose`:
    // shipped code must not require `using` of consumers, so the rule stays on
    // everywhere else and is the thing that catches a lapse. It flags both,
    // its `Symbol` list predating Explicit Resource Management, and it takes
    // no allowlist option, hence disabling it wholesale for these files.
    files: ['src/**/*.test.ts', 'src/**/*.test-d.ts', 'src/**/__fixtures__/**'],
    rules: {
      'unicorn/no-nonstandard-builtin-properties': 'off',
    },
  },
  {
    // Vite/Vitest/Prettier/Playwright config files must use a default
    // export; that's the contract those tools require.
    files: ['*.config.{js,ts}'],
    rules: {
      'import-x/no-default-export': 'off',
    },
  },
  {
    // Neither page has a project preview image yet to use as og:image;
    // og:title, og:type, and og:url are already set on the demo (see
    // `demo/index.html`).
    files: ['demo/**'],
    rules: {
      '@html-eslint/require-open-graph-protocol': 'off',
    },
  },
  {
    // The playground page (see `demo/playground`) is the only React in the
    // repo; the library itself is framework-free.
    files: ['demo/playground/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended],
  },
  {
    // Tailwind's own at-rules, which the CSS plugin does not know.
    files: ['demo/playground/styles.css'],
    rules: {
      'css/no-invalid-at-rules': 'off',
    },
  },
  {
    // The demo and playground run against the built package, so they import
    // `marking-menu`, never `src/`. Linting reads `dist/`, hence `yarn lint`
    // builds first.
    files: ['demo/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/src/**'],
              message: 'Import from `marking-menu`, not from the source.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['{src,demo}/**/__tests__/**'],
    rules: {
      // Kebab-case rejects the conventional `__tests__` and `__fixtures__`.
      // Treating them as roots skips checking them, but not the files and
      // folders inside.
      'unicorn/filename-case': [
        'error',
        { directoryRoots: [/(?:^|\/)__(?:tests|fixtures)__$/v] },
      ],
    },
  },
  {
    files: ['src/**/*.test.{js,ts}'],
    plugins: { vitest },
    languageOptions: {
      globals: vitest.environments.env.globals,
    },
    rules: {
      ...vitest.configs.recommended.rules,
      // Describe() is called with an imported function reference in some
      // files; the rule can't resolve the import to confirm it's a function.
      'vitest/valid-title': ['error', { allowArguments: true }],
      // `waitForMenuClosed`, `waitForFeedbackGone` and `expectFocused`
      // (`src/__tests__/__fixtures__/browser-menu.ts`) assert through
      // `expect.poll` internally; a test built entirely on one of them carries
      // no literal `expect` call for the rule to find otherwise.
      'vitest/expect-expect': [
        'error',
        {
          assertFunctionNames: [
            'expect',
            'waitForMenuClosed',
            'expectNoViolations',
            'waitForFeedbackGone',
            'expectFocused',
          ],
        },
      ],
    },
  },
]);
